# Generated by Django 5.2.4 on 2025-07-05 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_machine', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_operateur', models.CharField(max_length=50, unique=True)),
                ('lc', models.FloatField(help_text='Learning Curve (%)')),
                ('fc', models.FloatField(help_text='Facteur de charge (%)')),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tache', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('temps_standard', models.FloatField(help_text='Temps standard en minutes')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planification.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produit', models.CharField(max_length=50, unique=True)),
                ('cr', models.CharField(max_length=50)),
                ('quantite', models.IntegerField()),
                ('taches', models.ManyToManyField(blank=True, to='planification.tache')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceOperateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_initiale', models.FloatField(help_text='Performance initiale (temps en minutes)')),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planification.operateur')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planification.tache')),
            ],
            options={
                'unique_together': {('operateur', 'tache')},
            },
        ),
    ]
