# Generated by Django 5.2.4 on 2025-07-18 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_operateur', models.CharField(max_length=50, unique=True)),
                ('lc', models.FloatField(help_text='Learning Curve (%)')),
                ('fc', models.FloatField(help_text='Facteur de charge (%)')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produit', models.CharField(max_length=50, unique=True)),
                ('cr', models.CharField(max_length=50)),
                ('quantite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tache', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('machine', models.CharField(max_length=50)),
                ('temps_standard', models.FloatField(help_text='Temps standard en minutes')),
                ('ordre', models.PositiveIntegerField(default=1, help_text="Numéro d'ordre dans le processus (1, 2, 3...)", verbose_name='Ordre/Phase')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='planification.produit')),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('produit', 'id_tache')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceOperateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_initiale', models.FloatField(help_text='Performance initiale (temps en minutes)')),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planification.operateur')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planification.tache')),
            ],
            options={
                'unique_together': {('operateur', 'tache')},
            },
        ),
    ]
