# Generated by Django 5.2.4 on 2025-07-19 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operateur',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operateurs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produit',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operateur',
            name='fc',
            field=models.FloatField(help_text='forgetting curve (%)'),
        ),
        migrations.AlterField(
            model_name='performanceoperateur',
            name='performance_initiale',
            field=models.FloatField(help_text='Performance initiale (% max 115%)'),
        ),
    ]
