# Generated by Django 5.2.4 on 2025-07-05 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='machine',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='produit',
            name='taches',
        ),
        migrations.AddField(
            model_name='tache',
            name='produit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='planification.produit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tache',
            name='id_tache',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='tache',
            unique_together={('produit', 'id_tache')},
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
