# Generated by Django 5.2.4 on 2025-07-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planification', '0002_alter_tache_machine_remove_produit_taches_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tache',
            options={'ordering': ['ordre']},
        ),
        migrations.AddField(
            model_name='tache',
            name='ordre',
            field=models.PositiveIntegerField(default=1, help_text="Numéro d'ordre dans le processus (1, 2, 3...)", verbose_name='Ordre/Phase'),
        ),
    ]
