# Generated by Django 5.2.4 on 2025-07-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planification', '0002_operateur_user_produit_user_alter_operateur_fc_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tache',
            unique_together={('produit', 'ordre')},
        ),
        migrations.AlterField(
            model_name='tache',
            name='id_tache',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='machine',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tache',
            name='temps_standard',
            field=models.FloatField(),
        ),
    ]
