# Generated by Django 5.2.4 on 2025-07-14 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planification', '0004_operateur_user_produit_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operateur',
            name='user',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='user',
        ),
    ]
